[candle]
macro_interval = "1D"
micro_interval = "1H"
trade_interval = "4H" #下单时使用的周期

image_candle_count = 400  # 图像k线数量用于指定绘制k线图表的k线数量，周期与trade_interval一致
macro_interval_count = 90
micro_interval_count = 90
trade_interval_count = 90

[trade]
level = 5                   # 杠杆倍数
paper_trade = false
risk = 3                    # 单笔交易最高风险，单位为%
symbols = ["BTC-USDT-SWAP"] # 要运行的交易对                        
[indicator]
atr_period = 30 # ATR周期
ema = 20        # EMA周期

[llm]
main_model = "google/gemini-2.5-flash-lite"
reviewer_model = "google/gemini-2.5-flash-lite"
arbiter_model = "google/gemini-2.5-flash-lite"
reasoning_effort = "none"                     # none|low|medium|high
risk_analysis_model = "openai/gpt-oss-120b"
simple_analysis_model = "openai/gpt-oss-120b"
temperature = 0.2
visual_model = "google/gemini-2.5-flash-lite"
compress_llm = "openai/gpt-oss-120b"
max_compress = 42                             # 最大压缩次数，超过该次数的内容会被丢弃
